### ISSUE TITLE
Redirect launcher "learn more" button to actual initiative

### ISSUE THREAD

**Issue by iamisom** [Innervate/trendy-community#265]
link directly to the actual iniatitive:
https://dungeondefenders.com/2/initiatives/40

instead of the splash page:
https://dungeondefenders.com/2/initiatives

**Comment by rsyvarth** [comment]
The launcher already takes you to the initiative. I will update the home page of the website to do the same now.

**Comment by rsyvarth** [comment]
This change has been deployed.
