### ISSUE TITLE
Remove hashtag tagging

### ISSUE THREAD

**Issue by iamisom** [Innervate/trendy-community#267]
Can we remove hashtag tagging? There's a bug where sometimes the hashtag will appear like this [[user, #34234234]]. And since we don't actually use searching by hashtags, it would just be easier to let people make hashtags without that happening. (Usually a refresh fixes the issue, but it looks really buggy and doesn't actually have any functionality.)

**Comment by iamisom** [comment]
http://prntscr.com/ao6eo6

Here we go. So it does happen from time to time.

**Comment by iamisom** [comment]
Is this not something we can do easily?

**Comment by rsyvarth** [comment]
New content no longer supports the tagging functionality. Old content will still contain tags though. 

This has been deployed and is on production.
