### ISSUE TITLE
Add Abyss Lord emoticon

### ISSUE THREAD

**Issue by iamisom** [Innervate/trendy-community#268]
If we could have this tonight, that would be fantastic![b2a981a806952ea47e0e0ef68f6beaa2a1b14f3c4608f7115e pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/9043673/14264198/bc7b39ac-fa8c-11e5-9c56-9e4a83ecdd02.png)

**Comment by rsyvarth** [comment]
This is done and on production!
