### ISSUE TITLE
Relinking a member's Steam account

### ISSUE THREAD

**Issue by iamisom** [Innervate/trendy-community#270]
https://dungeondefenders.com/2/user/78500

Her new Steam account should be this:  http://steamcommunity.com/id/KittenKaboomi/

It's currently this:  http://steamcommunity.com/id/Zoltariel/

**Comment by adamlieb** [comment]
@AnthonyKinson when you start work tomorrow if you wouldn't mind doing this. Thanks!

**Comment by AnthonyKinson** [comment]
Tomorrow seems so far away.

This is now done.
