### ISSUE TITLE
New Forum Organization (Don't Do Until Friday)

### ISSUE THREAD

**Issue by iamisom** [Innervate/trendy-community#282]
We need to consolidate a few forums and change the name of two others:

1)  We need Game Feedback & Looking for Group merged into General Discussion.

2)  We need "Tech Support & Bug Reports" changed to "Tech Support."

There are a few more changes, but we can do those next week.

Thanks!

**Comment by rsyvarth** [comment]
Will do - tomorrow!

**Comment by rsyvarth** [comment]
Done

**Comment by iamisom** [comment]
Oops. It looks like I forgot to mention Website Feedback. Can you merge that into General Discussion, too, please? Thanks!!!

**Comment by rsyvarth** [comment]
Done!
